package dataservice

import "github.com/pedro-muniz/geekcontas/auth/model"

type UserDataInterface interface {
	//Insert adds a user to a database. The returned resultUser has a Id, which is auto generated by database
	Insert(user *model.User) (*model.User, error)

	// Update changes user information on the User.Id passed in.
	Update(user *model.User) (int64, error)

	// Remove deletes a user by user name from database.
	Delete(id int64) (int64, error)

	// Find retrieves a user from database based on a user's id
	Find(id int) (*model.User, error)

	// FindByEmail retrieves a user from database by User.Email
	FindByEmail(email string) (*model.User, error)

	// FindByEmailAndPassword retrieves a user from database by User.Email and User.Password
	FindByEmailAndPassword(email string, password string) (*model.User, error)
}
